[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc_version = "0.8.24"

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "@uniswap/v4-core/=lib/v4-core/",
    "@uniswap/v4-periphery/=lib/v4-periphery/",
    "@uniswap/permit2/=lib/permit2/",
    "@uniswap/universal-router/=lib/universal-router/",
    "@uniswap/v3-core/=lib/v3-core/",
    "@uniswap/v2-core/=lib/v2-core/",
    "solmate/=lib/solmate/",
    ]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
